version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Updating apt-get
      - echo Installing Maven

  pre_build:
    commands:
      - echo Pre-build phase started on date

  build:
    commands:
      - echo Build started on date
      - echo Building the Maven project...

  post_build:
    commands:
      - echo Post-build phase started on date

artifacts:
  files:
    discard-paths: yes
